                           TrackIt! Registration Form
                                 for Version 1.0

        Registrations are good for this version, and all future versions.

                                            Number of registrations  _____
    Pricing:

    $10 Per Registration........................................... $_____
    
    [ ] I'm enclosing the original cancelled check I used to
        register Record or SLearn to get $2.50 off TrackIt!       - $_____

    [ ] I admit voting for Bill Clinton. Due to the amount of
        money my vote cost you this past tax season, I'm enclosing
        an extra $5 as minor compensation.                        + $_____

    [ ] I have money to burn, and $10 means nothing to me, so I am
        enclosing a little extra.                                 + $_____


                                                              TOTAL $_____

    Make check or money order payable to Michael S. Hogg in U.S. funds.

    Please write for group discounts, government, corporate, or network
    license pricing.


    Name    ______________________________________________________________

    Company ______________________________________________________________

    Address ______________________________________________________________

            ______________________________________________________________

    City    ________________________________State _______ Zip ____________

    Where did you get TrackIt!? __________________________________________

       Mail to:

                 Michael S. Hogg
                 PO Box 8055
                 Hampton, Va 23666


    Comments, suggestions, constructive criticism:


    ______________________________________________________________________

    ______________________________________________________________________

    ______________________________________________________________________

    ______________________________________________________________________
