³   |--------------------------------------------------------------------|   ³
³ O | ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  | O ³
³   | ÛÛÛÛÛ ÛÛ  ÛÛ ÛÛ    ÛÛ     ÛÛÛÛÛÛ ÛÛÛÛÛÛ ÛÛÛÛÛÛ ÛÛ  ÛÛ ÛÛÛÛÛ    ÛÛ  |   ³
³ O | ÛÛ ÛÛ ÛÛ  ÛÛ ÛÛ    ÛÛ     ÛÛ       ÛÛ     ÛÛ   ÛÛÛ ÛÛ ÛÛ       ÛÛ  | O ³
³   | ÛÛÛÛÛ ÛÛ  ÛÛ ÛÛ    ÛÛ     ÛÛÛÛ     ÛÛ     ÛÛ   ÛÛÛÛÛÛ ÛÛÛÛÛ    ÛÛ  |   ³
³ O | ÛÛ ÛÛ ÛÛ  ÛÛ ÛÛ    ÛÛ     ÛÛ       ÛÛ     ÛÛ   ÛÛ ÛÛÛ    ÛÛ        | O ³
³   | ÛÛÛÛÛ ÛÛÛÛÛÛ ÛÛÛÛÛ ÛÛÛÛÛÛ ÛÛÛÛÛÛ   ÛÛ   ÛÛÛÛÛÛ ÛÛ  ÛÛ ÛÛÛÛÛ    ÛÛ  |   ³
³ O | ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  | O ³
³   |                                                                    |   ³
³ O | Main Bulletins                                                     | O ³
³   |                                                                    |   ³
³ O |                                                                    | O ³
³   | MiniBBS is a small BBS program which is written in the salt script |   ³
³ O | Language.  It's not an ordanary script language. It's very very    | O ³
³   | powerful.                                                          |   ³
³ O |                                                                    | O ³
³   |                                                                    |   ³
³ O |                                                                    | O ³
³   |                                                                    |   ³
³ O |                                                                    | O ³
³   | Welcome to MiniBBS.....                                            |   ³
³ O |                                                                    | O ³
³   | Se Ya Later                                                        |   ³
³ O |                   -> The Sysop                                     | O ³
³   |                                                                    |   ³
