echo off
cls
echo ีอต PRINTDOC, by: Jonathan Rapoport ฦออออออออออออออธ
echo ณ                                                  ณ
echo ณ This program will print MiniBBS's doccumentation ณ
echo ณ on your printer.                                 ณ
echo ณ                                                  ณ
echo ณ If you don't want to print the doccumentation,   ณ
echo ณ press CTRL-BREAK and answer Y, for yes.          ณ
echo ณ                                                  ณ
echo ิออออออออออออออออออออออออออออออออออออออออออออออออออพ
pause
type minibbs.doc >prn
cls
echo You may continue.  Please pass MiniBBS on so that everyone can enjoy it !
echo from : [Jonathan Rapoport]
echo off

