       ีอต TurboBBS v1.00 ฦอออออออออออออออออออออต Press '?' for Help! ฦอธ
       ณ                                                                ณ
       ณ                       ณ                      ณ                 ณ
       ณ (T)ype any file       ณ (Y)ell for SysOp     ณ (V)ersion       ณ
       ณ (F)iles avaliable     ณ (C)omment to SysOp   ณ (B)ulletin      ณ
       ณ (U)pload (send file)  ณ (A)pply for access   ณ (S)tatistics    ณ
       ณ (D)ownload (recieve)  ณ (*) Return to Opus   ณ (I)nit welcome  ณ
       ณ                       ณ                      ณ                 ณ
       ณฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤณฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤณฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤณ
       ณ                       ณ                      ณ                 ณ
       ณ (R)ead general mail   ณ (G)oodbye (Log Off)  ณ (E)nter message ณ
       ณ                       ณ                      ณ                 ณ
       ิออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออพ
