/* Configuration options for REND386 */

/* Written by Bernie Roehl, February 1993 */

#undef  ENABLE_ANIMATION 1            /* animation previewer */
#undef  ENABLE_STATE_SAVELOAD 1       /* world state save and load */
#define ENABLE_STATEMACH 1            /* Dave's state machine code */
#undef  ENABLE_DEPTHALTER 0           /* depthtype menu item */
#define ENABLE_RESIZE_ON_LOAD 1       /* plg loading prompts for scale */
#undef  JOY_INTS 0                    /* mask off ints while reading joy */
#undef  HD_CENTER 0                   /* HMD recentering possible */
#define SQRTL 1                       /* long sqrt available */

/* End of config.h */
