/* Header file for application-specific routines */

/* Written by Bernie Roehl, May 1992 */

/* Copyright 1992 by Dave Stampe and Bernie Roehl.
   May be freely used to write software for release into the public domain;
   all commercial endeavours MUST contact Bernie Roehl and Dave Stampe
   for permission to incorporate any part of this software into their
   products!
 */

extern void *find_name(void *list, char *name);
extern char *find_value(void *list, void *value);

/* End of demo.h */
