







                          BBS CONFIGURATION ASSISTANCE FORM


     BBS Name: ________________________________________________________________


                                 PCBOARD INFORMATION

     PCBoard version: _______.____

     Conference # (or NAME if supported) to Join at startup: __________


     Telix upload protocol letter: ____  Download protocol letter: ____

     If using the default protocol selected with the PCBoard T)rans. Protocol
     option, you may leave the entries below blank (The Liberator will simply
     use the default protocol).  The letters are only required if using
     separate protocols for uploading/downloading, or a different protocol than
     your default.  See the PCBoard protocol menu for the proper letters.

     PCBoard Upload protocol letter: ____  Download protocol letter: ____


     Upload The Liberator v2.32? ____    Upload a BBS Configuration? ____

     Mail Door: ___________  ProDoor: ___________   ProBank Door: ___________


                                 PRODOOR INFORMATION


     Telix upload protocol letter: ____    Download protocol letter: ____

     ProDoor Upload protocol letter: ____  Download protocol letter: ____


                       MAIL DOOR INFORMATION (Qmail/MarkMail)


     Door Type:  MarkMail___  Qmail v2___  Qmail v3___  Qmail v4___  
                 MegaMail___  NetMail ___  PCRelay ___

     Telix upload protocol letter: ____  Download protocol letter: ____

     If using the default protocol selected in the door, or if setting up for
     any door other than Qmail v3/4, you may leave the protocol entries below
     blank.  The letters are only required if using separate protocols for
     uploading/downloading, and if using a Qmail v3 or v4 door.

     Mail Door Upload protocol letter: ____  Download protocol letter: ____


     Packet ID (obtained from filename of a message packet): ________________
