


     The  L i b e r a t o r  v2.32                     Registration Form C-08.
     -------------------------------------------------------------------------
     Please print clearly.                [Office use] R#        D/R
     -------------------------------------------------------------------------

        Name: ___________________________________________________________

     Company: ___________________________________________________________

     Address: ___________________________________________________________

        City: _________________________   Prov/State: ___________________

         ZIP: _________________________        Phone: (_____)____________

     Country: ___________________________________________________________


                 Quantity      Price per registration
                 ------------------------------------
                  1 - 10       $24.95
                 11 - 20        19.95
                 21 - 50        14.95
                   51+           9.95

     # of Copies _______  x  $________ per reg. = Sub Total $____________

                   Ont. residents, add Provincial Sales Tax  ____________

                   Outside North America add $3.00 shipping +____________

                                                      TOTAL $____________

     One registered copy is sent (one 360K disk), plus a license to install
     the # of copies registered.  Orders are accepted in Canadian or U.S.
     currency.  Please mail your check, or M.O. to [NOTE: Postage to Canada
     from the U.S. was 5 cents extra at release date.]:

              Liberation Enterprises, 3091 Eglinton Ave E., Suite 602,
                          Scarboro, Ont., CANADA  M1J 2G1.

     Where did you obtain The Liberator?

     ____________________________________________________________________

     What do you use The Liberator for mainly (most important features)?

     ____________________________________________________________________

     ____________________________________________________________________

     What improvements or new features would you like to see added to the
     program in the future?  (Use back of page if necessary.)

     ____________________________________________________________________

     ____________________________________________________________________
